ADD Contact Form Section and Footer in the portfolio
joramot/capstone_portfolio pull request #4
Opened 2023-03-28 16:02 UTC by joramot

- Add contact form in index.html. First Step.

I will continue with the CSS classes to give style the form.

2023-03-28 17:43 UTC, alizaamir123 requested changes
I really appreciate the work you've done so far on this design.
I noticed that the design doesn't quite match the reference in Figma. I think it would be helpful to adjust a few elements to more closely align with the reference

2023-03-28 17:58 UTC, joramot commented
ok @alizaamir123 thanks, I will do it the changes.

2023-03-28 20:40 UTC, Kamba56 reviewed
Hi @joramot

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that **does not have contributions from your coding partner.** This Is a pair programming project, kindly work on it with your coding partner. there should be commit messages from your coding partner(s).

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-28 21:02 UTC, joramot commented
hello @Kamba56 my coding partner @alizaamir123 did contributions with her comments https://github.com/joramot/capstone_portfolio/pull/4#pullrequestreview-1361622340 
Is not correct?

2023-03-28 21:36 UTC, Kamba56 commented
> hello @Kamba56 my coding partner @alizaamir123 did contributions with her comments [#4 (review)](https://github.com/joramot/capstone_portfolio/pull/4#pullrequestreview-1361622340) Is not correct?

Hi @joramot, this is a pair programming project. This means that you and your partner should take turns being the driver and the navigator. The driver should write the code while the navigator makes suggestions. When it's time to switch turns, the driver pushes their changes to github. So commit messages from the parties involved should be visible on the PR. To achieve this, you need to add your partner as a contributor to the repo.

2023-03-28 21:56 UTC, joramot commented
@Kamba56  oooh!!, ok, I understand now, thanks so much @Kamba56 I will do it.

2023-03-28 22:42 UTC, adel-gu reviewed
# Status: INVALID ❌ 

**Hi @joramot 👋🏼** 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that contains the following issues:
-  The PR should contain a descriptive title and a summary that describe the achievements and the changes are been made in this milestone 👍🏼 
- This is a group project so the commit history should contain all the contributors' names for each commit according to how you split tasks among each other.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-03-28 22:55 UTC, joramot commented
Hello @adel-gu thanks for your time and observations, I will do the corrections in the description of the PR, and complete the peer-to-peer activity with my partners.

2023-03-29 19:34 UTC, ABDULALI3468 commented
@joramot It's me ABDUL ALI your Code Reviewer. I understand your problem you did a great job. I am reviewing your Pull request. Just wait for a few minutes. I will get back to you very soon!

2023-03-29 19:46 UTC, ABDULALI3468 requested changes
# Changes Required 👍 

Hi @joramot @alizaamir123 , 

<img src="https://media1.giphy.com/media/31Q36EHJ7C5ZoIMw79/giphy.gif"/>

Indeed you did an exceptional but still, there is room for changes to complete this project. 💯


## Highlights 
✅Your design looks great.
✅All linters are checked.
✅Project is professionally documented.
✅The right GitHub flow method has been used.
✅Professional pull request title and description.


 ## Required Changes ♻️

> **_Check the comments below to have a look at the required changes._**

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification.

> * This is My **GitHub**: ![GitHub followers](https://img.shields.io/github/followers/ABDULALI3468?label=ABDULALI&style=social)
> * This is My **Linkedin**: [![Linkedin Badge](https://img.shields.io/badge/-ABDUL%20ALI-blue?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/abdul-ali-5400bb216/)](https://www.linkedin.com/in/abdul-ali-5400bb216/)&nbsp;
> * This is My **Twitter**: [![Twitter Badge](https://img.shields.io/badge/-@mrabdul_ali_-1ca0f1?style=flat-square&labelColor=1ca0f1&logo=twitter&logoColor=white&link=https://twitter.com/mrabdul_ali)](https://twitter.com/mrabdul_ali)&nbsp;

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 19:46 UTC, ABDULALI3468 commented on index.html
> +      </form>
**1-** Please consider making the form elements in the center horizontally to make it look alike the Figma Template.

## Figma Design:-

![image](https://user-images.githubusercontent.com/94223367/228649721-2778e68c-8412-4c71-b794-7a956c8bbd80.png)


## Your Design:-

![image](https://user-images.githubusercontent.com/94223367/228649782-e881a63b-be31-4415-97c7-e61497dac60e.png)

**2-** Moreover, please consider adding or removing the outline from all the input including the text area field to match the design. The outline comes when the user clicks on the input.

```
outline: none;
```

2023-03-29 19:46 UTC, ABDULALI3468 commented on css/style.css
> +}
Please consider reducing the gap to like `20px` to make it closer to the design.

## Your Design:--

![image](https://user-images.githubusercontent.com/94223367/228650527-b40da39b-a4bc-40c5-bd77-1e523e7e9244.png)


## Figma Design:-

![image](https://user-images.githubusercontent.com/94223367/228650546-7675ca01-cb62-4e2e-9ea6-561f2f223c4d.png)


## Solution:-

Update the gap property to following:-

```
gap: "20px";
```

2023-03-29 21:15 UTC, Shisui6 approved these changes
Hi @joramot, 

# Approved 🪄
Your project is complete! There is nothing else to say other than... it's time to merge it 💎
Congratulations! 🎉 

## Highlights
- HTML validation done correctly ✅

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were simply missed by the previous reviewer, and addressing them will really improve your application._

You can also consider the following:

N/A

Cheers and Happy coding!🍻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-29 21:24 UTC, joramot commented
@Shisui6 thanks for your time.

2023-03-29 21:24 UTC, merged

2023-04-05 19:56 UTC, adel-gu commented
Hi @joramot 👋🏼, Sorry for the late replay, I gues the issue has been resolved 👍🏼.

Congratulations ✨